
public class Stacks {

	public static void main(String[] args) {
		//STACK WORKS ON LAST IN FIRST OUT
		//STACK CAN BE IMPLEMENTED THROUGH ARRAY, ARRAYLIST,LINKEDLIST
		//ARRAY IMPLEMENTATION IS HECTIC BECAUSE OF  ITS FIXED SIZE
		// WHEREAS ARRAYLIST AND LINKED LIST ARE OF VARIABLE LENGTH THUS, PREFERRED MORE
		

	}

}
